### ISSUE TITLE
18+ stream settings won't allow bots

### ISSUE THREAD

**Issue by aat440hz** [Infinity242/KickViewBot#1]
When a stream is set on 18+ the bots do not seem to work.

**Comment by Infinity242** [comment]
The bot automatically clicks the confirm 18 button on each stream, try it on the non-headless version.

**Comment by aat440hz** [comment]
Unfortunately this doesn't seem to work on Ubuntu or on the Windows 11 VirtualBox image. Have you tried it out recently because this feature is not working?

**Comment by Infinity242** [comment]
The issue was fixed in the most recent update! Thanks for letting me know!
